import { EMediaType } from '../enums/media-type.enum';
import { InvalidTmpMediaKeyException } from '../exceptions/invalid-tmp-media-key.exception';
import { MediaExtension } from './media-extension.vo';
import { TmpMediaKey } from './tmp-media-key.vo';

const png = MediaExtension.create(EMediaType.IMAGE, 'png');
const uuid = '0b6f6f7e-3c1a-4a52-9d3e-2f7a1c9b8e10';

describe('TmpMediaKey.create', () => {
  it('accepts a TMP key of the uploader with the declared extension', () => {
    const key = TmpMediaKey.create(`tmp/u1/${uuid}.png`, 'u1', png);

    expect(key.value).toBe(`tmp/u1/${uuid}.png`);
  });

  it.each([
    [`tmp/u2/${uuid}.png`, 'other user'],
    [`products/u1/${uuid}.png`, 'other folder'],
    [`tmp/u1/${uuid}.jpg`, 'other extension'],
    [`tmp/u1/../u2/${uuid}.png`, 'path traversal'],
    [`tmp/u1/not-a-uuid.png`, 'not generated by presign'],
    [`tmp/u1/${uuid}.png/extra`, 'trailing path'],
  ])('rejects %s (%s)', (raw) => {
    expect(() => TmpMediaKey.create(raw, 'u1', png)).toThrow(
      InvalidTmpMediaKeyException,
    );
  });
});
